# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/multi_xml/all/multi_xml.rbi
#
# multi_xml-0.8.1

module MultiXml
  def self.camelize(name); end
  def self.detect_parser; end
  def self.find_available_parser; end
  def self.find_loaded_parser; end
  def self.load_parser(name); end
  def self.normalize_input(xml); end
  def self.parse(xml, options = nil); end
  def self.parse_with_error_handling(io, original_input, xml_parser); end
  def self.parser; end
  def self.parser=(new_parser); end
  def self.raise_no_parser_error; end
  def self.resolve_parser(spec); end
  def self.try_require(library); end
end
class MultiXml::ParseError < StandardError
  def cause; end
  def initialize(message = nil, xml: nil, cause: nil); end
  def xml; end
end
class MultiXml::NoParserError < StandardError
end
class MultiXml::DisallowedTypeError < StandardError
  def initialize(type); end
  def type; end
end
module MultiXml::FileLike
  def content_type; end
  def content_type=(arg0); end
  def original_filename; end
  def original_filename=(arg0); end
end
module MultiXml::Helpers
  def apply_converter(hash, content, converter); end
  def convert_hash(hash, type, disallowed_types); end
  def convert_text_content(hash); end
  def disallowed_type?(type, disallowed_types); end
  def empty_value?(hash, type); end
  def extract_array_entries(hash, disallowed_types); end
  def find_array_entries(hash); end
  def self.convert_hash(hash, type, disallowed_types); end
  def self.convert_text_content(hash); end
  def self.disallowed_type?(type, disallowed_types); end
  def self.empty_value?(hash, type); end
  def self.extract_array_entries(hash, disallowed_types); end
  def self.find_array_entries(hash); end
  def self.symbolize_keys(data); end
  def self.typecast_array(array, disallowed_types); end
  def self.typecast_children(hash, disallowed_types); end
  def self.typecast_hash(hash, disallowed_types); end
  def self.typecast_xml_value(value, disallowed_types = nil); end
  def self.undasherize_keys(data); end
  def self.unwrap_if_simple(hash, value); end
  def self.wrap_and_typecast(entries, disallowed_types); end
  def symbolize_keys(data); end
  def transform_keys(data, &block); end
  def typecast_array(array, disallowed_types); end
  def typecast_children(hash, disallowed_types); end
  def typecast_hash(hash, disallowed_types); end
  def typecast_xml_value(value, disallowed_types = nil); end
  def undasherize_keys(data); end
  def unwrap_file_if_present(result); end
  def unwrap_if_simple(hash, value); end
  def wrap_and_typecast(entries, disallowed_types); end
end
