# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/oauth2/all/oauth2.rbi
#
# oauth2-2.0.18

module OAuth2
  def configure; end
  def self.config; end
  def self.configure; end
end
module OAuth2::Version
  extend VersionGem::Api
  extend VersionGem::Basic
end
module OAuth2::FilteredAttributes
  def inspect; end
  def self.included(base); end
end
module OAuth2::FilteredAttributes::ClassMethods
  def filtered_attribute_names; end
  def filtered_attributes(*attributes); end
end
class OAuth2::Error < StandardError
  def body; end
  def code; end
  def description; end
  def error_message(response_body, opts = nil); end
  def initialize(response); end
  def parse_error_description(code, description); end
  def response; end
end
class OAuth2::Authenticator
  def apply(params); end
  def apply_basic_auth(params); end
  def apply_client_id(params); end
  def apply_params_auth(params); end
  def basic_auth_header; end
  def id; end
  def initialize(id, secret, mode); end
  def mode; end
  def secret; end
  def self.encode_basic_auth(user, password); end
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
class OAuth2::ConnectionError < Faraday::ConnectionFailed
end
class OAuth2::TimeoutError < Faraday::TimeoutError
end
class OAuth2::Client
  def assertion; end
  def auth_code; end
  def authenticator; end
  def authorize_url(params = nil); end
  def build_access_token(response, access_token_opts, access_token_class); end
  def build_access_token_legacy(response, access_token_opts, extract_access_token); end
  def client_credentials; end
  def connection; end
  def connection=(arg0); end
  def execute_request(verb, url, opts = nil); end
  def get_token(params, access_token_opts = nil, extract_access_token = nil, &block); end
  def http_method; end
  def id; end
  def implicit; end
  def initialize(client_id, client_secret, options = nil, &block); end
  def oauth_debug_logging(builder); end
  def options; end
  def options=(arg0); end
  def params_to_req_opts(params); end
  def parse_response(response, access_token_opts); end
  def parse_response_legacy(response, access_token_opts, extract_access_token); end
  def parse_snaky_params_headers(params); end
  def password; end
  def redirection_params; end
  def request(verb, url, req_opts = nil, &block); end
  def revoke_token(token, token_type_hint = nil, params = nil, &block); end
  def revoke_url(params = nil); end
  def secret; end
  def site; end
  def site=(value); end
  def token_url(params = nil); end
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
module OAuth2::Strategy
end
class OAuth2::Strategy::Base
  def initialize(client); end
end
class OAuth2::Strategy::AuthCode < OAuth2::Strategy::Base
  def assert_valid_params(params); end
  def authorize_params(params = nil); end
  def authorize_url(params = nil); end
  def get_token(code, params = nil, opts = nil); end
end
class OAuth2::Strategy::Implicit < OAuth2::Strategy::Base
  def assert_valid_params(params); end
  def authorize_params(params = nil); end
  def authorize_url(params = nil); end
  def get_token(*); end
end
class OAuth2::Strategy::Password < OAuth2::Strategy::Base
  def authorize_url; end
  def get_token(username, password, params = nil, opts = nil); end
end
class OAuth2::Strategy::ClientCredentials < OAuth2::Strategy::Base
  def authorize_url; end
  def get_token(params = nil, opts = nil); end
end
class OAuth2::Strategy::Assertion < OAuth2::Strategy::Base
  def authorize_url; end
  def build_assertion(claims, encoding_opts); end
  def build_request(assertion, request_opts = nil); end
  def get_token(claims, encoding_opts, request_opts = nil, response_opts = nil); end
end
class OAuth2::AccessToken
  def [](key); end
  def client; end
  def configure_authentication!(opts, verb); end
  def convert_expires_at(expires_at); end
  def delete(path, opts = nil, &block); end
  def expired?; end
  def expires?; end
  def expires_at; end
  def expires_in; end
  def expires_latency; end
  def get(path, opts = nil, &block); end
  def headers; end
  def initialize(client, token, opts = nil); end
  def options; end
  def options=(arg0); end
  def params; end
  def patch(path, opts = nil, &block); end
  def post(path, opts = nil, &block); end
  def put(path, opts = nil, &block); end
  def refresh!(params = nil, access_token_opts = nil, &block); end
  def refresh(params = nil, access_token_opts = nil, &block); end
  def refresh_token; end
  def refresh_token=(arg0); end
  def request(verb, path, opts = nil, &block); end
  def response; end
  def response=(arg0); end
  def revoke!(params = nil, &block); end
  def revoke(params = nil, &block); end
  def self.extra_tokens_warning(supported_keys, key); end
  def self.from_hash(client, hash); end
  def self.from_kvform(client, kvform); end
  def self.no_tokens_warning(hash, key); end
  def to_hash; end
  def token; end
  extend OAuth2::FilteredAttributes::ClassMethods
  include OAuth2::FilteredAttributes
end
class OAuth2::Response
  def body; end
  def content_type; end
  def headers; end
  def initialize(response, parse: nil, snaky: nil, snaky_hash_klass: nil, **options); end
  def options; end
  def options=(arg0); end
  def parsed; end
  def parser; end
  def response; end
  def self.register_parser(key, mime_types, &block); end
  def status; end
end
