# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/snaky_hash/all/snaky_hash.rbi
#
# snaky_hash-2.0.3

module SnakyHash
end
module SnakyHash::Version
  extend VersionGem::Api
  extend VersionGem::Basic
end
class SnakyHash::Extensions
  def add(name, &block); end
  def has?(name); end
  def initialize; end
  def reset; end
  def run(value); end
end
module SnakyHash::Serializer
  def blank?(value); end
  def dump(obj); end
  def dump_hash(hash); end
  def dump_value(value); end
  def load(raw_hash); end
  def load_hash(hash); end
  def load_value(value); end
  def presence(value); end
  def self.extended(base); end
end
module SnakyHash::Serializer::Modulizer
  def self.to_extended_mod; end
end
module SnakyHash::Serializer::BackportedInstanceMethods
  def transform_values(&block); end
end
module SnakyHash::Serializer::ConvenienceInstanceMethods
  def dump; end
end
class SnakyHash::Snake < Module
  def included(base); end
  def initialize(key_type: nil, serializer: nil); end
end
module SnakyHash::Snake::SnakyModulizer
  def self.to_mod(key_type); end
end
class SnakyHash::StringKeyed < Hashie::Mash
  include Anonymous_Module_34
  include Anonymous_SnakyHash_Snake_35
end
module Anonymous_SnakyHash_Snake_35
end
module Anonymous_Module_34
  def convert_key(key); end
  def convert_value(val, duping = nil); end
  def underscore_string(str); end
end
class SnakyHash::SymbolKeyed < Hashie::Mash
  include Anonymous_Module_36
  include Anonymous_SnakyHash_Snake_37
end
module Anonymous_SnakyHash_Snake_37
end
module Anonymous_Module_36
  def convert_key(key); end
  def convert_value(val, duping = nil); end
  def underscore_string(str); end
end
class SnakyHash::Error < StandardError
end
